// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "contacts.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {
class tbh_fieldDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<tbh_field> {
} _tbh_field_default_instance_;
class tperson_mobileDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<tperson_mobile> {
} _tperson_mobile_default_instance_;
class tperson_bh_fieldDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<tperson_bh_field> {
} _tperson_bh_field_default_instance_;
class tpersonDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<tperson> {
} _tperson_default_instance_;
class tgroupDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<tgroup> {
} _tgroup_default_instance_;
class tcontactsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<tcontacts> {
} _tcontacts_default_instance_;

namespace protobuf_contacts_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[6];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tbh_field, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tbh_field, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tbh_field, name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson_mobile, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson_mobile, number_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson_bh_field, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson_bh_field, field_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson_bh_field, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson, money_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson, mobiles_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tperson, bh_fields_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tgroup, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tgroup, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tgroup, persons_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tgroup, fields_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcontacts, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcontacts, bh_fields_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcontacts, groups_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcontacts, timestamp_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(tbh_field)},
  { 7, -1, sizeof(tperson_mobile)},
  { 13, -1, sizeof(tperson_bh_field)},
  { 20, -1, sizeof(tperson)},
  { 29, -1, sizeof(tgroup)},
  { 37, -1, sizeof(tcontacts)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_tbh_field_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_tperson_mobile_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_tperson_bh_field_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_tperson_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_tgroup_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_tcontacts_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "contacts.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

}  // namespace

void TableStruct::Shutdown() {
  _tbh_field_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _tperson_mobile_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _tperson_bh_field_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _tperson_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _tgroup_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
  _tcontacts_default_instance_.Shutdown();
  delete file_level_metadata[5].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _tbh_field_default_instance_.DefaultConstruct();
  _tperson_mobile_default_instance_.DefaultConstruct();
  _tperson_bh_field_default_instance_.DefaultConstruct();
  _tperson_default_instance_.DefaultConstruct();
  _tgroup_default_instance_.DefaultConstruct();
  _tcontacts_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\016contacts.proto\022\002pb\"%\n\ttbh_field\022\n\n\002id\030"
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\"\273\001\n\007tperson\022\014\n\004name\030"
      "\001 \001(\t\022\r\n\005money\030\003 \001(\t\022#\n\007mobiles\030\n \003(\0132\022."
      "pb.tperson.mobile\022\'\n\tbh_fields\030\013 \003(\0132\024.p"
      "b.tperson.bh_field\032\030\n\006mobile\022\016\n\006number\030\001"
      " \001(\t\032+\n\010bh_field\022\020\n\010field_id\030\001 \001(\t\022\r\n\005va"
      "lue\030\002 \001(\t\"D\n\006tgroup\022\014\n\004name\030\001 \001(\t\022\034\n\007per"
      "sons\030\003 \003(\0132\013.pb.tperson\022\016\n\006fields\030\005 \003(\t\""
      "\\\n\ttcontacts\022 \n\tbh_fields\030\001 \003(\0132\r.pb.tbh"
      "_field\022\032\n\006groups\030\003 \003(\0132\n.pb.tgroup\022\021\n\tti"
      "mestamp\030\004 \001(\003b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 421);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "contacts.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_contacts_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tbh_field::kIdFieldNumber;
const int tbh_field::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tbh_field::tbh_field()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_contacts_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.tbh_field)
}
tbh_field::tbh_field(const tbh_field& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.id().size() > 0) {
    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.tbh_field)
}

void tbh_field::SharedCtor() {
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

tbh_field::~tbh_field() {
  // @@protoc_insertion_point(destructor:pb.tbh_field)
  SharedDtor();
}

void tbh_field::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void tbh_field::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tbh_field::descriptor() {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tbh_field& tbh_field::default_instance() {
  protobuf_contacts_2eproto::InitDefaults();
  return *internal_default_instance();
}

tbh_field* tbh_field::New(::google::protobuf::Arena* arena) const {
  tbh_field* n = new tbh_field;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tbh_field::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.tbh_field)
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool tbh_field::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.tbh_field)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->id().data(), static_cast<int>(this->id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tbh_field.id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tbh_field.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.tbh_field)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.tbh_field)
  return false;
#undef DO_
}

void tbh_field::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.tbh_field)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tbh_field.id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->id(), output);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tbh_field.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.tbh_field)
}

::google::protobuf::uint8* tbh_field::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.tbh_field)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tbh_field.id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->id(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tbh_field.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.tbh_field)
  return target;
}

size_t tbh_field::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.tbh_field)
  size_t total_size = 0;

  // string id = 1;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->id());
  }

  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tbh_field::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.tbh_field)
  GOOGLE_DCHECK_NE(&from, this);
  const tbh_field* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tbh_field>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.tbh_field)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.tbh_field)
    MergeFrom(*source);
  }
}

void tbh_field::MergeFrom(const tbh_field& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.tbh_field)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id().size() > 0) {

    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void tbh_field::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.tbh_field)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tbh_field::CopyFrom(const tbh_field& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.tbh_field)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tbh_field::IsInitialized() const {
  return true;
}

void tbh_field::Swap(tbh_field* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tbh_field::InternalSwap(tbh_field* other) {
  id_.Swap(&other->id_);
  name_.Swap(&other->name_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tbh_field::GetMetadata() const {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// tbh_field

// string id = 1;
void tbh_field::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& tbh_field::id() const {
  // @@protoc_insertion_point(field_get:pb.tbh_field.id)
  return id_.GetNoArena();
}
void tbh_field::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.tbh_field.id)
}
#if LANG_CXX11
void tbh_field::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.tbh_field.id)
}
#endif
void tbh_field::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.tbh_field.id)
}
void tbh_field::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.tbh_field.id)
}
::std::string* tbh_field::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:pb.tbh_field.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* tbh_field::release_id() {
  // @@protoc_insertion_point(field_release:pb.tbh_field.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void tbh_field::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:pb.tbh_field.id)
}

// string name = 2;
void tbh_field::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& tbh_field::name() const {
  // @@protoc_insertion_point(field_get:pb.tbh_field.name)
  return name_.GetNoArena();
}
void tbh_field::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.tbh_field.name)
}
#if LANG_CXX11
void tbh_field::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.tbh_field.name)
}
#endif
void tbh_field::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.tbh_field.name)
}
void tbh_field::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.tbh_field.name)
}
::std::string* tbh_field::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:pb.tbh_field.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* tbh_field::release_name() {
  // @@protoc_insertion_point(field_release:pb.tbh_field.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void tbh_field::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pb.tbh_field.name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tperson_mobile::kNumberFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tperson_mobile::tperson_mobile()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_contacts_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.tperson.mobile)
}
tperson_mobile::tperson_mobile(const tperson_mobile& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  number_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.number().size() > 0) {
    number_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.number_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.tperson.mobile)
}

void tperson_mobile::SharedCtor() {
  number_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

tperson_mobile::~tperson_mobile() {
  // @@protoc_insertion_point(destructor:pb.tperson.mobile)
  SharedDtor();
}

void tperson_mobile::SharedDtor() {
  number_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void tperson_mobile::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tperson_mobile::descriptor() {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tperson_mobile& tperson_mobile::default_instance() {
  protobuf_contacts_2eproto::InitDefaults();
  return *internal_default_instance();
}

tperson_mobile* tperson_mobile::New(::google::protobuf::Arena* arena) const {
  tperson_mobile* n = new tperson_mobile;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tperson_mobile::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.tperson.mobile)
  number_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool tperson_mobile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.tperson.mobile)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_number()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->number().data(), static_cast<int>(this->number().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tperson.mobile.number"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.tperson.mobile)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.tperson.mobile)
  return false;
#undef DO_
}

void tperson_mobile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.tperson.mobile)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string number = 1;
  if (this->number().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->number().data(), static_cast<int>(this->number().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.mobile.number");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->number(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.tperson.mobile)
}

::google::protobuf::uint8* tperson_mobile::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.tperson.mobile)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string number = 1;
  if (this->number().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->number().data(), static_cast<int>(this->number().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.mobile.number");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->number(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.tperson.mobile)
  return target;
}

size_t tperson_mobile::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.tperson.mobile)
  size_t total_size = 0;

  // string number = 1;
  if (this->number().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->number());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tperson_mobile::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.tperson.mobile)
  GOOGLE_DCHECK_NE(&from, this);
  const tperson_mobile* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tperson_mobile>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.tperson.mobile)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.tperson.mobile)
    MergeFrom(*source);
  }
}

void tperson_mobile::MergeFrom(const tperson_mobile& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.tperson.mobile)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.number().size() > 0) {

    number_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.number_);
  }
}

void tperson_mobile::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.tperson.mobile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tperson_mobile::CopyFrom(const tperson_mobile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.tperson.mobile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tperson_mobile::IsInitialized() const {
  return true;
}

void tperson_mobile::Swap(tperson_mobile* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tperson_mobile::InternalSwap(tperson_mobile* other) {
  number_.Swap(&other->number_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tperson_mobile::GetMetadata() const {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// tperson_mobile

// string number = 1;
void tperson_mobile::clear_number() {
  number_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& tperson_mobile::number() const {
  // @@protoc_insertion_point(field_get:pb.tperson.mobile.number)
  return number_.GetNoArena();
}
void tperson_mobile::set_number(const ::std::string& value) {
  
  number_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.tperson.mobile.number)
}
#if LANG_CXX11
void tperson_mobile::set_number(::std::string&& value) {
  
  number_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.tperson.mobile.number)
}
#endif
void tperson_mobile::set_number(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  number_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.tperson.mobile.number)
}
void tperson_mobile::set_number(const char* value, size_t size) {
  
  number_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.tperson.mobile.number)
}
::std::string* tperson_mobile::mutable_number() {
  
  // @@protoc_insertion_point(field_mutable:pb.tperson.mobile.number)
  return number_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* tperson_mobile::release_number() {
  // @@protoc_insertion_point(field_release:pb.tperson.mobile.number)
  
  return number_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void tperson_mobile::set_allocated_number(::std::string* number) {
  if (number != NULL) {
    
  } else {
    
  }
  number_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), number);
  // @@protoc_insertion_point(field_set_allocated:pb.tperson.mobile.number)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tperson_bh_field::kFieldIdFieldNumber;
const int tperson_bh_field::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tperson_bh_field::tperson_bh_field()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_contacts_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.tperson.bh_field)
}
tperson_bh_field::tperson_bh_field(const tperson_bh_field& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  field_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.field_id().size() > 0) {
    field_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field_id_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.tperson.bh_field)
}

void tperson_bh_field::SharedCtor() {
  field_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

tperson_bh_field::~tperson_bh_field() {
  // @@protoc_insertion_point(destructor:pb.tperson.bh_field)
  SharedDtor();
}

void tperson_bh_field::SharedDtor() {
  field_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void tperson_bh_field::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tperson_bh_field::descriptor() {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tperson_bh_field& tperson_bh_field::default_instance() {
  protobuf_contacts_2eproto::InitDefaults();
  return *internal_default_instance();
}

tperson_bh_field* tperson_bh_field::New(::google::protobuf::Arena* arena) const {
  tperson_bh_field* n = new tperson_bh_field;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tperson_bh_field::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.tperson.bh_field)
  field_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool tperson_bh_field::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.tperson.bh_field)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string field_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->field_id().data(), static_cast<int>(this->field_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tperson.bh_field.field_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), static_cast<int>(this->value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tperson.bh_field.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.tperson.bh_field)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.tperson.bh_field)
  return false;
#undef DO_
}

void tperson_bh_field::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.tperson.bh_field)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string field_id = 1;
  if (this->field_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->field_id().data(), static_cast<int>(this->field_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.bh_field.field_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->field_id(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.bh_field.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.tperson.bh_field)
}

::google::protobuf::uint8* tperson_bh_field::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.tperson.bh_field)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string field_id = 1;
  if (this->field_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->field_id().data(), static_cast<int>(this->field_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.bh_field.field_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->field_id(), target);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.bh_field.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.tperson.bh_field)
  return target;
}

size_t tperson_bh_field::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.tperson.bh_field)
  size_t total_size = 0;

  // string field_id = 1;
  if (this->field_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->field_id());
  }

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tperson_bh_field::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.tperson.bh_field)
  GOOGLE_DCHECK_NE(&from, this);
  const tperson_bh_field* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tperson_bh_field>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.tperson.bh_field)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.tperson.bh_field)
    MergeFrom(*source);
  }
}

void tperson_bh_field::MergeFrom(const tperson_bh_field& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.tperson.bh_field)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.field_id().size() > 0) {

    field_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field_id_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void tperson_bh_field::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.tperson.bh_field)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tperson_bh_field::CopyFrom(const tperson_bh_field& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.tperson.bh_field)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tperson_bh_field::IsInitialized() const {
  return true;
}

void tperson_bh_field::Swap(tperson_bh_field* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tperson_bh_field::InternalSwap(tperson_bh_field* other) {
  field_id_.Swap(&other->field_id_);
  value_.Swap(&other->value_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tperson_bh_field::GetMetadata() const {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// tperson_bh_field

// string field_id = 1;
void tperson_bh_field::clear_field_id() {
  field_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& tperson_bh_field::field_id() const {
  // @@protoc_insertion_point(field_get:pb.tperson.bh_field.field_id)
  return field_id_.GetNoArena();
}
void tperson_bh_field::set_field_id(const ::std::string& value) {
  
  field_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.tperson.bh_field.field_id)
}
#if LANG_CXX11
void tperson_bh_field::set_field_id(::std::string&& value) {
  
  field_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.tperson.bh_field.field_id)
}
#endif
void tperson_bh_field::set_field_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  field_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.tperson.bh_field.field_id)
}
void tperson_bh_field::set_field_id(const char* value, size_t size) {
  
  field_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.tperson.bh_field.field_id)
}
::std::string* tperson_bh_field::mutable_field_id() {
  
  // @@protoc_insertion_point(field_mutable:pb.tperson.bh_field.field_id)
  return field_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* tperson_bh_field::release_field_id() {
  // @@protoc_insertion_point(field_release:pb.tperson.bh_field.field_id)
  
  return field_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void tperson_bh_field::set_allocated_field_id(::std::string* field_id) {
  if (field_id != NULL) {
    
  } else {
    
  }
  field_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), field_id);
  // @@protoc_insertion_point(field_set_allocated:pb.tperson.bh_field.field_id)
}

// string value = 2;
void tperson_bh_field::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& tperson_bh_field::value() const {
  // @@protoc_insertion_point(field_get:pb.tperson.bh_field.value)
  return value_.GetNoArena();
}
void tperson_bh_field::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.tperson.bh_field.value)
}
#if LANG_CXX11
void tperson_bh_field::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.tperson.bh_field.value)
}
#endif
void tperson_bh_field::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.tperson.bh_field.value)
}
void tperson_bh_field::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.tperson.bh_field.value)
}
::std::string* tperson_bh_field::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:pb.tperson.bh_field.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* tperson_bh_field::release_value() {
  // @@protoc_insertion_point(field_release:pb.tperson.bh_field.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void tperson_bh_field::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:pb.tperson.bh_field.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tperson::kNameFieldNumber;
const int tperson::kMoneyFieldNumber;
const int tperson::kMobilesFieldNumber;
const int tperson::kBhFieldsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tperson::tperson()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_contacts_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.tperson)
}
tperson::tperson(const tperson& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      mobiles_(from.mobiles_),
      bh_fields_(from.bh_fields_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  money_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.money().size() > 0) {
    money_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.money_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.tperson)
}

void tperson::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  money_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

tperson::~tperson() {
  // @@protoc_insertion_point(destructor:pb.tperson)
  SharedDtor();
}

void tperson::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  money_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void tperson::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tperson::descriptor() {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tperson& tperson::default_instance() {
  protobuf_contacts_2eproto::InitDefaults();
  return *internal_default_instance();
}

tperson* tperson::New(::google::protobuf::Arena* arena) const {
  tperson* n = new tperson;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tperson::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.tperson)
  mobiles_.Clear();
  bh_fields_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  money_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool tperson::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.tperson)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tperson.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string money = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_money()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->money().data(), static_cast<int>(this->money().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tperson.money"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pb.tperson.mobile mobiles = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_mobiles()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pb.tperson.bh_field bh_fields = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_bh_fields()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.tperson)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.tperson)
  return false;
#undef DO_
}

void tperson::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.tperson)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string money = 3;
  if (this->money().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->money().data(), static_cast<int>(this->money().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.money");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->money(), output);
  }

  // repeated .pb.tperson.mobile mobiles = 10;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->mobiles_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->mobiles(static_cast<int>(i)), output);
  }

  // repeated .pb.tperson.bh_field bh_fields = 11;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bh_fields_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->bh_fields(static_cast<int>(i)), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.tperson)
}

::google::protobuf::uint8* tperson::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.tperson)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string money = 3;
  if (this->money().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->money().data(), static_cast<int>(this->money().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tperson.money");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->money(), target);
  }

  // repeated .pb.tperson.mobile mobiles = 10;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->mobiles_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        10, this->mobiles(static_cast<int>(i)), deterministic, target);
  }

  // repeated .pb.tperson.bh_field bh_fields = 11;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bh_fields_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        11, this->bh_fields(static_cast<int>(i)), deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.tperson)
  return target;
}

size_t tperson::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.tperson)
  size_t total_size = 0;

  // repeated .pb.tperson.mobile mobiles = 10;
  {
    unsigned int count = static_cast<unsigned int>(this->mobiles_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->mobiles(static_cast<int>(i)));
    }
  }

  // repeated .pb.tperson.bh_field bh_fields = 11;
  {
    unsigned int count = static_cast<unsigned int>(this->bh_fields_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->bh_fields(static_cast<int>(i)));
    }
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string money = 3;
  if (this->money().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->money());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tperson::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.tperson)
  GOOGLE_DCHECK_NE(&from, this);
  const tperson* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tperson>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.tperson)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.tperson)
    MergeFrom(*source);
  }
}

void tperson::MergeFrom(const tperson& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.tperson)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  mobiles_.MergeFrom(from.mobiles_);
  bh_fields_.MergeFrom(from.bh_fields_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.money().size() > 0) {

    money_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.money_);
  }
}

void tperson::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.tperson)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tperson::CopyFrom(const tperson& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.tperson)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tperson::IsInitialized() const {
  return true;
}

void tperson::Swap(tperson* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tperson::InternalSwap(tperson* other) {
  mobiles_.InternalSwap(&other->mobiles_);
  bh_fields_.InternalSwap(&other->bh_fields_);
  name_.Swap(&other->name_);
  money_.Swap(&other->money_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tperson::GetMetadata() const {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// tperson

// string name = 1;
void tperson::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& tperson::name() const {
  // @@protoc_insertion_point(field_get:pb.tperson.name)
  return name_.GetNoArena();
}
void tperson::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.tperson.name)
}
#if LANG_CXX11
void tperson::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.tperson.name)
}
#endif
void tperson::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.tperson.name)
}
void tperson::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.tperson.name)
}
::std::string* tperson::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:pb.tperson.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* tperson::release_name() {
  // @@protoc_insertion_point(field_release:pb.tperson.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void tperson::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pb.tperson.name)
}

// string money = 3;
void tperson::clear_money() {
  money_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& tperson::money() const {
  // @@protoc_insertion_point(field_get:pb.tperson.money)
  return money_.GetNoArena();
}
void tperson::set_money(const ::std::string& value) {
  
  money_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.tperson.money)
}
#if LANG_CXX11
void tperson::set_money(::std::string&& value) {
  
  money_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.tperson.money)
}
#endif
void tperson::set_money(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  money_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.tperson.money)
}
void tperson::set_money(const char* value, size_t size) {
  
  money_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.tperson.money)
}
::std::string* tperson::mutable_money() {
  
  // @@protoc_insertion_point(field_mutable:pb.tperson.money)
  return money_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* tperson::release_money() {
  // @@protoc_insertion_point(field_release:pb.tperson.money)
  
  return money_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void tperson::set_allocated_money(::std::string* money) {
  if (money != NULL) {
    
  } else {
    
  }
  money_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), money);
  // @@protoc_insertion_point(field_set_allocated:pb.tperson.money)
}

// repeated .pb.tperson.mobile mobiles = 10;
int tperson::mobiles_size() const {
  return mobiles_.size();
}
void tperson::clear_mobiles() {
  mobiles_.Clear();
}
const ::pb::tperson_mobile& tperson::mobiles(int index) const {
  // @@protoc_insertion_point(field_get:pb.tperson.mobiles)
  return mobiles_.Get(index);
}
::pb::tperson_mobile* tperson::mutable_mobiles(int index) {
  // @@protoc_insertion_point(field_mutable:pb.tperson.mobiles)
  return mobiles_.Mutable(index);
}
::pb::tperson_mobile* tperson::add_mobiles() {
  // @@protoc_insertion_point(field_add:pb.tperson.mobiles)
  return mobiles_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::tperson_mobile >*
tperson::mutable_mobiles() {
  // @@protoc_insertion_point(field_mutable_list:pb.tperson.mobiles)
  return &mobiles_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::tperson_mobile >&
tperson::mobiles() const {
  // @@protoc_insertion_point(field_list:pb.tperson.mobiles)
  return mobiles_;
}

// repeated .pb.tperson.bh_field bh_fields = 11;
int tperson::bh_fields_size() const {
  return bh_fields_.size();
}
void tperson::clear_bh_fields() {
  bh_fields_.Clear();
}
const ::pb::tperson_bh_field& tperson::bh_fields(int index) const {
  // @@protoc_insertion_point(field_get:pb.tperson.bh_fields)
  return bh_fields_.Get(index);
}
::pb::tperson_bh_field* tperson::mutable_bh_fields(int index) {
  // @@protoc_insertion_point(field_mutable:pb.tperson.bh_fields)
  return bh_fields_.Mutable(index);
}
::pb::tperson_bh_field* tperson::add_bh_fields() {
  // @@protoc_insertion_point(field_add:pb.tperson.bh_fields)
  return bh_fields_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::tperson_bh_field >*
tperson::mutable_bh_fields() {
  // @@protoc_insertion_point(field_mutable_list:pb.tperson.bh_fields)
  return &bh_fields_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::tperson_bh_field >&
tperson::bh_fields() const {
  // @@protoc_insertion_point(field_list:pb.tperson.bh_fields)
  return bh_fields_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tgroup::kNameFieldNumber;
const int tgroup::kPersonsFieldNumber;
const int tgroup::kFieldsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tgroup::tgroup()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_contacts_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.tgroup)
}
tgroup::tgroup(const tgroup& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      persons_(from.persons_),
      fields_(from.fields_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.tgroup)
}

void tgroup::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

tgroup::~tgroup() {
  // @@protoc_insertion_point(destructor:pb.tgroup)
  SharedDtor();
}

void tgroup::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void tgroup::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tgroup::descriptor() {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tgroup& tgroup::default_instance() {
  protobuf_contacts_2eproto::InitDefaults();
  return *internal_default_instance();
}

tgroup* tgroup::New(::google::protobuf::Arena* arena) const {
  tgroup* n = new tgroup;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tgroup::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.tgroup)
  persons_.Clear();
  fields_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool tgroup::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.tgroup)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tgroup.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pb.tperson persons = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_persons()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string fields = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_fields()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fields(this->fields_size() - 1).data(),
            static_cast<int>(this->fields(this->fields_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.tgroup.fields"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.tgroup)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.tgroup)
  return false;
#undef DO_
}

void tgroup::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.tgroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tgroup.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .pb.tperson persons = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->persons_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->persons(static_cast<int>(i)), output);
  }

  // repeated string fields = 5;
  for (int i = 0, n = this->fields_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fields(i).data(), static_cast<int>(this->fields(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tgroup.fields");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->fields(i), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.tgroup)
}

::google::protobuf::uint8* tgroup::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.tgroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tgroup.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .pb.tperson persons = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->persons_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->persons(static_cast<int>(i)), deterministic, target);
  }

  // repeated string fields = 5;
  for (int i = 0, n = this->fields_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fields(i).data(), static_cast<int>(this->fields(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.tgroup.fields");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->fields(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.tgroup)
  return target;
}

size_t tgroup::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.tgroup)
  size_t total_size = 0;

  // repeated .pb.tperson persons = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->persons_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->persons(static_cast<int>(i)));
    }
  }

  // repeated string fields = 5;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->fields_size());
  for (int i = 0, n = this->fields_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->fields(i));
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tgroup::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.tgroup)
  GOOGLE_DCHECK_NE(&from, this);
  const tgroup* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tgroup>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.tgroup)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.tgroup)
    MergeFrom(*source);
  }
}

void tgroup::MergeFrom(const tgroup& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.tgroup)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  persons_.MergeFrom(from.persons_);
  fields_.MergeFrom(from.fields_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void tgroup::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.tgroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tgroup::CopyFrom(const tgroup& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.tgroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tgroup::IsInitialized() const {
  return true;
}

void tgroup::Swap(tgroup* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tgroup::InternalSwap(tgroup* other) {
  persons_.InternalSwap(&other->persons_);
  fields_.InternalSwap(&other->fields_);
  name_.Swap(&other->name_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tgroup::GetMetadata() const {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// tgroup

// string name = 1;
void tgroup::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& tgroup::name() const {
  // @@protoc_insertion_point(field_get:pb.tgroup.name)
  return name_.GetNoArena();
}
void tgroup::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.tgroup.name)
}
#if LANG_CXX11
void tgroup::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.tgroup.name)
}
#endif
void tgroup::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.tgroup.name)
}
void tgroup::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.tgroup.name)
}
::std::string* tgroup::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:pb.tgroup.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* tgroup::release_name() {
  // @@protoc_insertion_point(field_release:pb.tgroup.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void tgroup::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pb.tgroup.name)
}

// repeated .pb.tperson persons = 3;
int tgroup::persons_size() const {
  return persons_.size();
}
void tgroup::clear_persons() {
  persons_.Clear();
}
const ::pb::tperson& tgroup::persons(int index) const {
  // @@protoc_insertion_point(field_get:pb.tgroup.persons)
  return persons_.Get(index);
}
::pb::tperson* tgroup::mutable_persons(int index) {
  // @@protoc_insertion_point(field_mutable:pb.tgroup.persons)
  return persons_.Mutable(index);
}
::pb::tperson* tgroup::add_persons() {
  // @@protoc_insertion_point(field_add:pb.tgroup.persons)
  return persons_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::tperson >*
tgroup::mutable_persons() {
  // @@protoc_insertion_point(field_mutable_list:pb.tgroup.persons)
  return &persons_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::tperson >&
tgroup::persons() const {
  // @@protoc_insertion_point(field_list:pb.tgroup.persons)
  return persons_;
}

// repeated string fields = 5;
int tgroup::fields_size() const {
  return fields_.size();
}
void tgroup::clear_fields() {
  fields_.Clear();
}
const ::std::string& tgroup::fields(int index) const {
  // @@protoc_insertion_point(field_get:pb.tgroup.fields)
  return fields_.Get(index);
}
::std::string* tgroup::mutable_fields(int index) {
  // @@protoc_insertion_point(field_mutable:pb.tgroup.fields)
  return fields_.Mutable(index);
}
void tgroup::set_fields(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:pb.tgroup.fields)
  fields_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void tgroup::set_fields(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:pb.tgroup.fields)
  fields_.Mutable(index)->assign(std::move(value));
}
#endif
void tgroup::set_fields(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  fields_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:pb.tgroup.fields)
}
void tgroup::set_fields(int index, const char* value, size_t size) {
  fields_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pb.tgroup.fields)
}
::std::string* tgroup::add_fields() {
  // @@protoc_insertion_point(field_add_mutable:pb.tgroup.fields)
  return fields_.Add();
}
void tgroup::add_fields(const ::std::string& value) {
  fields_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:pb.tgroup.fields)
}
#if LANG_CXX11
void tgroup::add_fields(::std::string&& value) {
  fields_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:pb.tgroup.fields)
}
#endif
void tgroup::add_fields(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  fields_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:pb.tgroup.fields)
}
void tgroup::add_fields(const char* value, size_t size) {
  fields_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:pb.tgroup.fields)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
tgroup::fields() const {
  // @@protoc_insertion_point(field_list:pb.tgroup.fields)
  return fields_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
tgroup::mutable_fields() {
  // @@protoc_insertion_point(field_mutable_list:pb.tgroup.fields)
  return &fields_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tcontacts::kBhFieldsFieldNumber;
const int tcontacts::kGroupsFieldNumber;
const int tcontacts::kTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tcontacts::tcontacts()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_contacts_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.tcontacts)
}
tcontacts::tcontacts(const tcontacts& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      bh_fields_(from.bh_fields_),
      groups_(from.groups_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:pb.tcontacts)
}

void tcontacts::SharedCtor() {
  timestamp_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

tcontacts::~tcontacts() {
  // @@protoc_insertion_point(destructor:pb.tcontacts)
  SharedDtor();
}

void tcontacts::SharedDtor() {
}

void tcontacts::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tcontacts::descriptor() {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tcontacts& tcontacts::default_instance() {
  protobuf_contacts_2eproto::InitDefaults();
  return *internal_default_instance();
}

tcontacts* tcontacts::New(::google::protobuf::Arena* arena) const {
  tcontacts* n = new tcontacts;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tcontacts::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.tcontacts)
  bh_fields_.Clear();
  groups_.Clear();
  timestamp_ = GOOGLE_LONGLONG(0);
}

bool tcontacts::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.tcontacts)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.tbh_field bh_fields = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_bh_fields()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pb.tgroup groups = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_groups()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 timestamp = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.tcontacts)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.tcontacts)
  return false;
#undef DO_
}

void tcontacts::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.tcontacts)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.tbh_field bh_fields = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bh_fields_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->bh_fields(static_cast<int>(i)), output);
  }

  // repeated .pb.tgroup groups = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->groups_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->groups(static_cast<int>(i)), output);
  }

  // int64 timestamp = 4;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->timestamp(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.tcontacts)
}

::google::protobuf::uint8* tcontacts::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.tcontacts)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.tbh_field bh_fields = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bh_fields_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->bh_fields(static_cast<int>(i)), deterministic, target);
  }

  // repeated .pb.tgroup groups = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->groups_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->groups(static_cast<int>(i)), deterministic, target);
  }

  // int64 timestamp = 4;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->timestamp(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.tcontacts)
  return target;
}

size_t tcontacts::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.tcontacts)
  size_t total_size = 0;

  // repeated .pb.tbh_field bh_fields = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->bh_fields_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->bh_fields(static_cast<int>(i)));
    }
  }

  // repeated .pb.tgroup groups = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->groups_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->groups(static_cast<int>(i)));
    }
  }

  // int64 timestamp = 4;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tcontacts::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.tcontacts)
  GOOGLE_DCHECK_NE(&from, this);
  const tcontacts* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tcontacts>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.tcontacts)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.tcontacts)
    MergeFrom(*source);
  }
}

void tcontacts::MergeFrom(const tcontacts& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.tcontacts)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  bh_fields_.MergeFrom(from.bh_fields_);
  groups_.MergeFrom(from.groups_);
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void tcontacts::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.tcontacts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tcontacts::CopyFrom(const tcontacts& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.tcontacts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tcontacts::IsInitialized() const {
  return true;
}

void tcontacts::Swap(tcontacts* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tcontacts::InternalSwap(tcontacts* other) {
  bh_fields_.InternalSwap(&other->bh_fields_);
  groups_.InternalSwap(&other->groups_);
  std::swap(timestamp_, other->timestamp_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tcontacts::GetMetadata() const {
  protobuf_contacts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_contacts_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// tcontacts

// repeated .pb.tbh_field bh_fields = 1;
int tcontacts::bh_fields_size() const {
  return bh_fields_.size();
}
void tcontacts::clear_bh_fields() {
  bh_fields_.Clear();
}
const ::pb::tbh_field& tcontacts::bh_fields(int index) const {
  // @@protoc_insertion_point(field_get:pb.tcontacts.bh_fields)
  return bh_fields_.Get(index);
}
::pb::tbh_field* tcontacts::mutable_bh_fields(int index) {
  // @@protoc_insertion_point(field_mutable:pb.tcontacts.bh_fields)
  return bh_fields_.Mutable(index);
}
::pb::tbh_field* tcontacts::add_bh_fields() {
  // @@protoc_insertion_point(field_add:pb.tcontacts.bh_fields)
  return bh_fields_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::tbh_field >*
tcontacts::mutable_bh_fields() {
  // @@protoc_insertion_point(field_mutable_list:pb.tcontacts.bh_fields)
  return &bh_fields_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::tbh_field >&
tcontacts::bh_fields() const {
  // @@protoc_insertion_point(field_list:pb.tcontacts.bh_fields)
  return bh_fields_;
}

// repeated .pb.tgroup groups = 3;
int tcontacts::groups_size() const {
  return groups_.size();
}
void tcontacts::clear_groups() {
  groups_.Clear();
}
const ::pb::tgroup& tcontacts::groups(int index) const {
  // @@protoc_insertion_point(field_get:pb.tcontacts.groups)
  return groups_.Get(index);
}
::pb::tgroup* tcontacts::mutable_groups(int index) {
  // @@protoc_insertion_point(field_mutable:pb.tcontacts.groups)
  return groups_.Mutable(index);
}
::pb::tgroup* tcontacts::add_groups() {
  // @@protoc_insertion_point(field_add:pb.tcontacts.groups)
  return groups_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::tgroup >*
tcontacts::mutable_groups() {
  // @@protoc_insertion_point(field_mutable_list:pb.tcontacts.groups)
  return &groups_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::tgroup >&
tcontacts::groups() const {
  // @@protoc_insertion_point(field_list:pb.tcontacts.groups)
  return groups_;
}

// int64 timestamp = 4;
void tcontacts::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 tcontacts::timestamp() const {
  // @@protoc_insertion_point(field_get:pb.tcontacts.timestamp)
  return timestamp_;
}
void tcontacts::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:pb.tcontacts.timestamp)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
